version: "3.6"
services:
  pgsql:
    build: './docker/database'
    container_name: pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Mengganti port host menjadi 5434
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork
  goservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goservice
    env_file: .env # Menggunakan file .env dari host
    environment:
      SERVER_HOST: goservice
      SERVER_PORT: 8080
      DATABASE_HOST: pgsql
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - pgsql
    networks:
      - mynetwork # Pastikan goservice menggunakan jaringan yang sama
  # nginx:
  #  build: "./docker/nginx"
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - goservice
  #  networks:
  #    - mynetwork  # Pastikan ini sesuai jika Anda menggunakan jaringan khusus

networks:
  mynetwork:
    # Jika menggunakan jaringan khusus
    driver: bridge

volumes:
  pgdata:
  api_volume:
